# Dockerfile.prod.frontend

FROM node:20-alpine AS builder
WORKDIR /app
# Копируем package.json
COPY frontend/package*.json ./
# Устанавливаем зависимости
RUN npm ci
# Копируем весь код фронтенда
COPY frontend/ .

# Сборка
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1