# docker-compose.prod.yml

services:

  # -------------------- BACKEND --------------------

  backend:
    container_name: promo_ml_backend
    image: asperansky/promo-ml:stage5
    restart: unless-stopped


    environment:
      ENV: prod
      LOG_LEVEL: INFO
      ML_MODEL_DIR: /app/models
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/promo
      REDIS_URL: redis://redis:6379/0

    volumes:
      - backend-logs:/app/logs
      - models:/app/models/current

#    ports:
#      - "8000:8000"
      # - "8000"

    expose:
      - "8000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - promo_net

  # -------------------- FRONTEND --------------------

  frontend:
    container_name: promo_ml_frontend
    image: asperansky/promo-ml-front:stage5
    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - backend

    networks:
      - promo_net


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # -------------------- POSTGRES --------------------

  postgres:
    image: postgres:15
    container_name: promo_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: promo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql

    ports:
      - "5432:5432"

    networks:
      - promo_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  # ------------ POSTGRES EXPORTER ------------------
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: promo_postgres_exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/promo?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - promo_net


  # -------------------- REDIS --------------------

  redis:
    image: redis:7
    container_name: promo_redis
    restart: unless-stopped

    volumes:
      - redis-data:/data

    ports:
      - "6379"
      # - "6379:6379"

    networks:
      - promo_net

    healthcheck: # ← ДОБАВЬ ЭТОТ БЛОК
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # -------------------- NGINX --------------------

  nginx:
    image: nginx:1.25
    container_name: promo_nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx

    depends_on:
      - backend
      - frontend

    networks:
      - promo_net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # -------------------- LOKI --------------------

  loki:
    image: grafana/loki:2.9.2
    container_name: promo_loki
    restart: unless-stopped

    volumes:
      - loki-data:/loki

    ports:
      - "3100:3100"

    networks:
      - promo_net

  # -------------------- PROMTAIL --------------------

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promo_promtail
    restart: unless-stopped

    volumes:
      - backend-logs:/app/logs
      - nginx-logs:/var/log/nginx:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - loki

    networks:
      - promo_net

  # -------------------- GRAFANA --------------------

  grafana:
    image: grafana/grafana:10.2.2
    container_name: promo_grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - GF_SERVER_ROOT_URL=http://192.168.18.73:3000
      - GF_SERVER_DOMAIN=192.168.18.73
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_COOKIE_SECURE=false

    volumes:
      - grafana-data:/var/lib/grafana

    networks:
      - promo_net

  # -------------------- PROMETHEUS --------------------

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: promo_prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - prometheus-data:/prometheus
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - promo_net

# -------------------- NETWORK --------------------

networks:
  promo_net:
    driver: bridge

# -------------------- VOLUMES --------------------

volumes:
  postgres-data:
  postgres-logs:
  grafana-data:
  loki-data:
  redis-data:
  backend-logs:
  nginx-logs:
  prometheus-data:
  models: