# app/ml/feature_config.yaml

inference_features:
  # 🔥 Промо-акция
  - name: promo_id
    type: string
    required: false
    default: ""

  # Временные параметры
  - name: week
    type: integer
    required: true
    default: "1"

  - name: month
    type: integer
    required: true
    default: "1"

  # Товар и категория
  - name: sku
    type: string
    required: true
    default: ""

  - name: category
    type: string
    required: true
    default: ""

  # Цены
  - name: regular_price
    type: number
    required: true
    default: "0.0"

  - name: promo_price
    type: number
    required: true
    default: "0.0"

  # Магазин и локация
  - name: store_id
    type: string
    required: true
    default: ""

  - name: region
    type: string
    required: true
    default: ""

  - name: store_location_type
    type: string
    required: true
    default: ""

  - name: format_assortment
    type: string
    required: true
    default: ""

  # Маркетинг и механики
  - name: adv_carrier
    type: string
    required: false
    default: ""

  - name: adv_material
    type: string
    required: false
    default: ""

  - name: promo_mechanics
    type: string
    required: false
    default: ""

  - name: marketing_type
    type: string
    required: true
    default: ""


  # Справочные поля
  - name: analog_sku
    type: array
    required: false
    default: []


computed_features:
  - name: price_drop_percent
    type: number
    formula: |
      ((regular_price - promo_price) / regular_price) * 100 if regular_price > 0 else 0