"""initial_schema

Revision ID: 13460cc58f93
Revises: 
Create Date: 2025-12-25 17:36:44.794966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13460cc58f93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_model')),
    sa.UniqueConstraint('name', name=op.f('uq_ml_model_name'))
    )
    op.create_table('product',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Мягкое удаление'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Время мягкого удаления (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_table('promo',
    sa.Column('promo_code', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Мягкое удаление'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Время мягкого удаления (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo'))
    )
    op.create_index(op.f('ix_promo_promo_code'), 'promo', ['promo_code'], unique=True)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ml_model_id', sa.Integer(), nullable=False),
    sa.Column('predicted_sales', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ml_model_id'], ['ml_model.id'], name=op.f('fk_prediction_ml_model_id_ml_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction'))
    )
    op.create_index(op.f('ix_prediction_ml_model_id'), 'prediction', ['ml_model_id'], unique=False)
    op.create_table('promo_position',
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата действия промо'),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('sales_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Мягкое удаление'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Время мягкого удаления (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_promo_position_product_id_product')),
    sa.ForeignKeyConstraint(['promo_id'], ['promo.id'], name=op.f('fk_promo_position_promo_id_promo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_position'))
    )
    op.create_index(op.f('ix_promo_position_product_id'), 'promo_position', ['product_id'], unique=False)
    op.create_index(op.f('ix_promo_position_promo_id'), 'promo_position', ['promo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_position_promo_id'), table_name='promo_position')
    op.drop_index(op.f('ix_promo_position_product_id'), table_name='promo_position')
    op.drop_table('promo_position')
    op.drop_index(op.f('ix_prediction_ml_model_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_promo_promo_code'), table_name='promo')
    op.drop_table('promo')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_table('product')
    op.drop_table('ml_model')
    # ### end Alembic commands ###
